apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: guestbook-go-project
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: guestbook
  type: NodePort
